version: 2
updates: 
  - package-ecosystem: "cargo"
    directory: "/"
    schedule: 
      interval: "monthly"
    ignore:
      # ignore patch updates to all cargo crates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
